name: multi_updater
description: >
  A Flutter package that checks for app updates via Firebase Remote Config or a custom JSON endpoint,
  and shows users an update prompt with a direct link to App Store or Play Store.
version: 1.0.0

homepage: https://github.com/Akhmedov2705/multi_updater
repository: https://github.com/Akhmedov2705/multi_updater
issue_tracker: https://github.com/Akhmedov2705/multi_updater/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_remote_config: ^5.4.5
  http: ^1.4.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

platforms:
  android:
  ios:

topics:
  - multi_updater
  - update
  - firebase
  - remote-config
  - app-store
  - play-store
